'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConfigurationUploadDownload

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hidFailAfterSeconds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidFailAfterSeconds As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidMultiPLC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidMultiPLC As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidLineTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidLineTypeID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbDnldAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbDnldAux As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbUpldAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbUpldAux As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbDnldCompScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbDnldCompScan As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbUpldCompScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbUpldCompScan As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbDnldCompName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbDnldCompName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbUpldCompName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbUpldCompName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbDnldTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbDnldTool As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbUpldTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbUpldTool As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbDnldStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbDnldStation As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbUpldStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbUpldStation As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbDnldProdCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbDnldProdCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbUpldProdCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbUpldProdCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbDnldUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbDnldUser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbUpldUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbUpldUser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbDnldAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbDnldAux As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbUpldAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbUpldAux As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbDnldCompScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbDnldCompScan As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbUpldCompScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbUpldCompScan As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbDnldCompName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbDnldCompName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbUpldCompName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbUpldCompName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbDnldTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbDnldTool As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbUpldTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbUpldTool As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbDnldStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbDnldStation As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbUpldStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbUpldStation As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbDnldProdCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbDnldProdCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbUpldProdCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbUpldProdCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbDnldUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbDnldUser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbUpldUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbUpldUser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbDnldQualAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbDnldQualAux As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbUpldQualAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbUpldQualAux As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbDnldQualCompScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbDnldQualCompScan As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbUpldQualCompScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbUpldQualCompScan As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbDnldQualCompName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbDnldQualCompName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbUpldQualCompName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbUpldQualCompName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbDnldQualTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbDnldQualTool As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbUpldQualTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbUpldQualTool As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbDnldQualStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbDnldQualStation As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbUpldQualStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbUpldQualStation As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbDnldQualProdCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbDnldQualProdCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbUpldQualProdCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbUpldQualProdCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbDnldQualUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbDnldQualUser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidpbUpldQualUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpbUpldQualUser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbDnldQualAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbDnldQualAux As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbUpldQualAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbUpldQualAux As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbDnldQualCompScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbDnldQualCompScan As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbUpldQualCompScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbUpldQualCompScan As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbDnldQualCompName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbDnldQualCompName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbUpldQualCompName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbUpldQualCompName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbDnldQualTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbDnldQualTool As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbUpldQualTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbUpldQualTool As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbDnldQualStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbDnldQualStation As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbUpldQualStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbUpldQualStation As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbDnldQualProdCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbDnldQualProdCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbUpldQualProdCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbUpldQualProdCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbDnldQualUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbDnldQualUser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidInitpbUpldQualUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInitpbUpldQualUser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddLineNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddLineNumber As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmdRefreshAndClearComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshAndClearComplete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefresh As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hlAuxTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlAuxTask As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblAuxCfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAuxCfg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPLCAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPLCAux As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPLCQualAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPLCQualAux As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJITAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJITAux As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdDnldAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDnldAux As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdDnldQualAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDnldQualAux As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdUpldAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpldAux As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdUpldQualAux control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpldQualAux As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hlCompScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlCompScan As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Label8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPLCCompScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPLCCompScan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPLCQualCompScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPLCQualCompScan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJITCompScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJITCompScan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdDnldCompScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDnldCompScan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdDnldQualCompScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDnldQualCompScan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdUpldCompScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpldCompScan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdUpldQualCompScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpldQualCompScan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hlCompName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlCompName As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Label9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPLCCompName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPLCCompName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPLCQualCompName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPLCQualCompName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJITCompName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJITCompName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdDnldCompName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDnldCompName As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdDnldQualCompName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDnldQualCompName As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdUpldCompName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpldCompName As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdUpldQualCompName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpldQualCompName As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hlTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlTool As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblToolCfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblToolCfg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPLCTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPLCTool As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPLCQualTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPLCQualTool As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJITTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJITTool As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdDnldTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDnldTool As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdDnldQualTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDnldQualTool As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdUpldTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpldTool As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdUpldQualTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpldQualTool As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hlStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlStation As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Label11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPLCStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPLCStation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPLCQualStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPLCQualStation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJITStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJITStation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdDnldStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDnldStation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdDnldQualStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDnldQualStation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdUpldStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpldStation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdUpldQualStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpldQualStation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hlProdCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlProdCode As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Label12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPLCProdCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPLCProdCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPLCQualProdCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPLCQualProdCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJITProdCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJITProdCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdDnldProdCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDnldProdCode As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdDnldQualProdCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDnldQualProdCode As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdUpldProdCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpldProdCode As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdUpldQualProdCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpldQualProdCode As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hlUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlUser As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPLCUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPLCUser As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPLCQualUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPLCQualUser As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJITUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJITUser As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdDnldUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDnldUser As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdDnldQualUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDnldQualUser As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdUpldUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpldUser As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdUpldQualUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpldQualUser As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As LTMS_Master.Site
        Get
            Return CType(MyBase.Master, LTMS_Master.Site)
        End Get
    End Property
End Class
